name: "Sonar-less Code Scan"
description: "SonarQube Code Scan without a hosted SonarQube Server"
author: "GitRicko"

inputs:
  sonar-project-name:
    description: "SonarQube Project Name"
    required: true
    default: ${{github.event.repository.name}}
  sonar-project-key:
    description: "Name to say hello to"
    required: true
    default: "World2"

runs:
  using: "composite"
  steps:
    - name: Hello World
      run: make -C scripts sonar-action
      shell: bash
      env:
        SONAR_PROJECT_NAME: ${{inputs.sonar-project-name}}
        SONAR_PROJECT_KEY: ${{inputs.sonar-project-key}}