name: CI

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        default: 'chew'

  push:
    branches:
      - '**'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sonar-less-Scan
        uses: ./
        with:
          name: 'fred'