name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  sonarless-cli-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sonarless install test
        run: |
          cat ./install.sh | bash

      - name: Check Install
        run: |
          grep "sonarless" ~/.bashrc
          ls -lah $HOME/.sonarless/makefile.sh
          $HOME/.sonarless/makefile.sh help

      - name: Sonarless uninstall test
        run: |
          $HOME/.sonarless/makefile.sh uninstall

      - name: Check Uninstall
        run: |
          if [[ -d "$HOME/.sonarless" ]]; then
            echo "sonarless scriptlet is not uninstalled - bad"
            exit 1
          else
            echo "sonarless scriptlet removed - good"
          fi

  sonarless-action-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Sample Code for Scanning
        run: |
          git clone https://github.com/SonarSource/sonar-scanner-npm.git
          pwd
          ls -lahd */*

      - name: Sonarless Scan
        uses: ./
        with:
          sonar-source-path: './sonar-scanner-npm'
          sonar-metrics-path: './blahblah.json'

      - name: Check Sonar Metrics
        run: |
          echo "Checking for any vulnerabilities in Sonar Metrics JSON"
          VULN=$(cat ./blahblah.json | jq -r '.component.measures[] | select(.metric == "vulnerabilities").value')
          echo "# of vulnerabilities = ${VULN}"
          [ ${VULN} -eq "0" ]
