name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  sonarless-action-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sonarless Scan
        uses: ./
        with:
          sonar-source-path: 'test-src'
          sonar-metrics-path: './blahblah.json'

      - name: Check Sonar Metrics
        run: |
          echo "Checking for bugs in Sonar Metrics JSON"
          jq -r ./blahblah.json
