name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  sonarless-cli-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sonarless curl install test
        run: |
          if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
            echo "You are inside a Git repository."
          else
            echo "You are not inside a Git repository."
          fi
          echo "Current branch: ${GITHUB_REF#refs/heads/}"
          export BRANCH=$(git branch --show-current)
          curl -s "https://raw.githubusercontent.com/gitricko/sonarless/${BRANCH}/install.sh" | bash

      - name: Sonarless help
        run: |
          sonarless help

  sonarless-action-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sonarless Scan
        uses: ./
        with:
          sonar-source-path: 'test-src'
          sonar-metrics-path: './blahblah.json'

      - name: Check Sonar Metrics
        run: |
          echo "Checking for any vulnerabilities in Sonar Metrics JSON"
          VULN=$(cat ./blahblah.json | jq -r '.component.measures[] | select(.metric == "vulnerabilities").value')
          echo "# of vulnerabilities = ${VULN}"
          [ ${VULN} -eq "0" ]
